import path from "node:path";
import url from "node:url";

import eslint from "@eslint/js";
import pluginVitest from "@vitest/eslint-plugin";
import { defineConfig, globalIgnores } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig([
  // contract.d.ts is generated by openapi-typescript; its style is not ours.
  globalIgnores(["dist/**", "coverage/**", "src/schema/contract.d.ts"]),
  eslint.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ["eslint.config.mjs"],
        },
        tsconfigRootDir: path.dirname(url.fileURLToPath(import.meta.url)),
      },
    },
  },
  {
    rules: {
      "no-console": "error",
      // `??` would keep an empty env var that must fall through (src/context.ts).
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
    },
  },
  {
    // `enable-annotation` gates annotations, and a call site that bypasses the
    // gate posts one the caller turned off without failing anything.
    files: ["src/**/*.ts"],
    ignores: ["src/annotations.ts"],
    rules: {
      "no-restricted-properties": [
        "error",
        {
          object: "core",
          property: "warning",
          message: "Use warn() from src/annotations.ts.",
        },
        {
          object: "core",
          property: "notice",
          message: "Use notice() from src/annotations.ts.",
        },
      ],
    },
  },
  {
    files: ["src/__tests__/**/*.ts"],
    plugins: { vitest: pluginVitest },
    rules: {
      ...pluginVitest.configs.recommended.rules,
      // Mock factories hand back `vi.fn()`s, which are `any` by construction.
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
    },
  },
]);
